/*
 * ProvaJpanelList.java
 *
 * Created on 22 agosto 2008, 11.24
 */

package pdcmvoice.p2p;

import java.awt.event.ActionListener;
import javax.swing.Action;
import javax.swing.JList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author  Laura
 */
//questa clase serve solo da test per vedere se carica la lista quando laci p2plisttest. E lo fa 
// e quando selezioni l'utente dalla lista e cliccci call visualizza l'indirizzo 
//sulla textbox
public class ProvaJpanelList extends javax.swing.JFrame {

    UserNodeListModel model;
    String address;
    /** Creates new form ProvaJpanelList */
    public ProvaJpanelList(Action listener ,UserNodeListModel listmodel) {
//        model = listmodel;        
        initComponents(listener,listmodel);
        
    }

    public int getSelectedIndex(){
        return onlinelist.getSelectedIndex();
    }

    public void update(){
        onlinelist.validate();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void initComponents() {//GEN-BEGIN:initComponents

        jScrollPane1 = new javax.swing.JScrollPane();
        onlinelist = new javax.swing.JList();
        call = new javax.swing.JButton();
        addr = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 100, 100));
        setMinimumSize(new java.awt.Dimension(100000, 150000));

        onlinelist.setModel(model);
        onlinelist.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        onlinelist.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                onlinelistValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(onlinelist);

        call.setText("call");
        call.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                callMouseClicked(evt);
            }
        });
        call.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                callActionPerformed(evt);
            }
        });

        addr.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(call)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(addr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(call))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(addr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
    }//GEN-END:initComponents

    private void initComponents(Action listener,UserNodeListModel listmodel) {

        jScrollPane1 = new javax.swing.JScrollPane();
        onlinelist = new javax.swing.JList();
        call = new javax.swing.JButton();
        addr = new javax.swing.JTextField();

        setBounds(new java.awt.Rectangle(0, 0, 100, 100));
        setMinimumSize(new java.awt.Dimension(100000, 150000));

        onlinelist.setModel(listmodel);
        onlinelist.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        onlinelist.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                onlinelistValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(onlinelist);

        call.setText("call");
        call.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                callMouseClicked(evt);
            }
        });
        call.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                callActionPerformed(evt);
            }
        });

        addr.setText("jTextField1");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 86, 86)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                .add(call)    
                .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 46, 46)
                .add(addr,org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
                );
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addGap(86, 86, 86)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                    .addComponent(call)
//                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addGap(46, 46, 46)
//                .addComponent(addr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addContainerGap(126, Short.MAX_VALUE))
//        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED,23,23)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 30, 30)
                        .add(call))
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED,71,71)
                        .add(addr, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94,Short.MAX_VALUE))
        );
        
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(layout.createSequentialGroup()
//                        .addGap(23, 23, 23)
//                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addGap(30, 30, 30)
//                        .addComponent(call))
//                    .addGroup(layout.createSequentialGroup()
//                        .addGap(71, 71, 71)
//                        .addComponent(addr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                .addContainerGap(94, Short.MAX_VALUE))
//        );
    }// </editor-fold>
private void callActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_callActionPerformed
    System.out.println(address);
}//GEN-LAST:event_callActionPerformed

private void callMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_callMouseClicked
   addr.setText(address);
}//GEN-LAST:event_callMouseClicked

private void onlinelistValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_onlinelistValueChanged

    this.validate();
    if(!evt.getValueIsAdjusting()){
            JList online = (JList)evt.getSource();
            UserNode selectedItem = (UserNode)online.getSelectedValue();          
            address = selectedItem.getAddress();
        }
}//GEN-LAST:event_onlinelistValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addr;
    private javax.swing.JButton call;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList onlinelist;
    // End of variables declaration//GEN-END:variables


}

