package blitztalk.client;

import java.awt.event.ActionListener;
/**
 * Call info UI.  Generated by NetBeans.
 * Added a few methods for setting values, and a listener
 * 
 * @author  tcarney
 */
public class CallUI extends javax.swing.JFrame {
    
    /** Creates new form CallUI */
    public CallUI(ActionListener l, String name) {
        initComponents(l, name);
    }
    
    public void setButtonText(String text) {
    	button.setText(text);
    }
    
    public void setText(String text) {
    	message.setText(text);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents(ActionListener l, String name) {
        button = new javax.swing.JButton();
        message = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Call");
        button.setText("Hang up");
        button.addActionListener(l);

        message.setText("Calling: " + name);
        message.setFocusable(false);
        message.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(51, 51, 51)
                        .add(button))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(message, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(message)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 39, Short.MAX_VALUE)
                .add(button)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button;
    private javax.swing.JLabel message;
    // End of variables declaration//GEN-END:variables
    
}
