/*
 * ProvaJpanelList.java
 *
 * Created on 22 agosto 2008, 11.24
 */

package pdcmvoice.p2p;

import java.awt.event.ActionListener;
import javax.swing.JList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author  Laura
 */
//classe inutile
//serviva per vedere un frame con li jlist ma non va il connect del client....
//usa action listener perchè ho preso spunto dablitztalk è per manipolare
//l'evento call associato al bottone me è da fare
public class ProvaJpanelList extends javax.swing.JFrame {

    /** Creates new form ProvaJpanelList */
    public ProvaJpanelList(ActionListener listener, UserNodeListModel listmodel) {
        initComponents(listener, listmodel);
        
    }

    public int getSelectedIndex(){
        return online.getSelectedIndex();
    }

    public void update(){
        online.validate();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents(ActionListener listener, UserNodeListModel listmodel){
       
        jScrollPane1 = new javax.swing.JScrollPane();
        online = new javax.swing.JList();
        call = new javax.swing.JButton();

        online.setModel(listmodel);
        online.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        online.addListSelectionListener(new ListListener());
        jScrollPane1.setViewportView(online);

        call.setText("Call");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(call))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(call)
                .addContainerGap(129, Short.MAX_VALUE))
        );
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        online = new javax.swing.JList();
        call = new javax.swing.JButton();

        online.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(online);

        call.setText("Call");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(call))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(call)
                .addContainerGap(129, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton call;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList online;
    // End of variables declaration//GEN-END:variables


}
class ListListener implements ListSelectionListener{
   
  //  JList online;
    String address ;
    
//    public ListListener(JList online){
//        this.online = online;
//    }
    //prende l'indirizzo dello user selezionato 
    public void valueChanged(ListSelectionEvent e) {
        if(!e.getValueIsAdjusting()){
            JList online = (JList)e.getSource();
            //preleva il nome dell'utente selezionato nella lista
            String selectedItem = (String)online.getSelectedValue();          
            //con lo username estraggo lo userNode
            UserNode user  = UserNode.getUserNode(selectedItem);
            address = user.getAddress();
        }
        
    }

}
